package com.muyuan.common.core.constant;

public interface RedisConst {

    short SHORT_TRUE_VALUE = 1;

    short SHORT_FALSE_VALUE = 0;

    String TOKEN_KEY_PREFIX = "COMMON:TOKEN:";

    String OPERATOR_ROLE_MENU_KEY_PREFIX = "OPERATOR:ROLE:MENU:";

    String OPERATOR_ROLE_PERM_KEY_PREFIX = "OPERATOR:ROLE:PERM:";

    String MERCHANT_ROLE_MENU_KEY_PREFIX = "OPERATOR:ROLE:MENU:";

    String MERCHANT_ROLE_PERM_KEY_PREFIX = "OPERATOR:ROLE:PERM:";

    String MEMBER_ROLE_MENU_KEY_PREFIX = "MEMBER:ROLE:MENU:";

    String MEMBER_ROLE_PERM_KEY_PREFIX = "MEMBER:SYS:ROLE:PERM:";

    String ALL_PLACE_HOLDER = "*";

    String SYS_DATA_DICT = "SYS:DICT:";

    String COUNT_KEY = "COUNT:";
}
