package com.muyuan.common.core.constant;

public enum RedisConst {



    TOKEN_KEY_PREFIX,

     OPERATOR_ROLE_MENU_KEY_PREFIX,

     OPERATOR_ROLE_PERM_KEY_PREFIX ,

     MERCHANT_ROLE_MENU_KEY_PREFIX,

     MERCHANT_ROLE_PERM_KEY_PREFIX,

     MEMBER_ROLE_MENU_KEY_PREFIX,

     MEMBER_ROLE_PERM_KEY_PREFIX ,

     ALL_PLACE_HOLDER ,

     SYS_DATA_DICT ,

     COUNT_KEY ;
}
